name: Destroy Resources
on:
  workflow_dispatch:
env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  destroy-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      id: init
      working-directory: terraform
      run: terraform init

    - name: Terraform destroy
      id: destroy
      working-directory: terraform
      run: terraform destroy --auto-approve

  remove-tfstate-bucket:
    runs-on: ubuntu-latest 
    needs: destroy-resources
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Remove bucket
      run: |
        BUCKET_NAME="project2-2-resources"
        aws s3 rm s3://$BUCKET_NAME --recursive
        aws s3api delete-bucket --bucket $BUCKET_NAME
